import { NextResponse } from 'next/server'
import { createClient } from '@/lib/supabase/server'
import { getUserTier } from '@/lib/subscription/tier'

export async function GET() {
  try {
    const supabase = createClient()
    const {
      data: { user },
      error: authError,
    } = await supabase.auth.getUser()

    if (authError || !user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 })
    }

    // Premium only feature
    const tier = await getUserTier(user.id)
    if (tier !== 'premium') {
      return NextResponse.json(
        { error: 'This feature is available for premium users only' },
        { status: 403 }
      )
    }

    // Fetch user data and profile
    const [userResult, profileResult, symptomLogsResult] = await Promise.all([
      supabase.from('users').select('*').eq('id', user.id).single(),
      supabase
        .from('user_profiles')
        .select('*')
        .eq('user_id', user.id)
        .single(),
      supabase
        .from('symptom_logs')
        .select('*')
        .eq('user_id', user.id)
        .gte(
          'date',
          new Date(Date.now() - 30 * 24 * 60 * 60 * 1000)
            .toISOString()
            .split('T')[0]
        )
        .order('date', { ascending: true }),
    ])

    const userData = userResult.data
    const profileData = profileResult.data
    const symptomLogs = symptomLogsResult.data || []

    // Calculate symptom trends over the last 30 days
    const symptomAverages: Record<string, number> = {}
    const symptomCounts: Record<string, number> = {}

    for (const log of symptomLogs) {
      const symptoms = log.symptoms as Record<string, number>
      for (const [symptom, value] of Object.entries(symptoms)) {
        if (!symptomAverages[symptom]) {
          symptomAverages[symptom] = 0
          symptomCounts[symptom] = 0
        }
        symptomAverages[symptom] += value
        symptomCounts[symptom]++
      }
    }

    // Compute averages
    const symptomTrends: Record<
      string,
      { average: number; entries: number }
    > = {}
    for (const [symptom, total] of Object.entries(symptomAverages)) {
      symptomTrends[symptom] = {
        average:
          Math.round((total / symptomCounts[symptom]) * 100) / 100,
        entries: symptomCounts[symptom],
      }
    }

    // Identify most severe symptoms
    const severeSymptoms = Object.entries(symptomTrends)
      .filter(([, data]) => data.average >= 3)
      .sort((a, b) => b[1].average - a[1].average)
      .map(([symptom, data]) => ({
        symptom: symptom.replace(/_/g, ' '),
        averageSeverity: data.average,
      }))

    // Build the report
    const age = userData?.date_of_birth
      ? Math.floor(
          (Date.now() - new Date(userData.date_of_birth).getTime()) /
            (365.25 * 24 * 60 * 60 * 1000)
        )
      : null

    const report = {
      report_type: 'Doctor Visit Summary',
      generated_at: new Date().toISOString(),
      period: 'Last 30 days',
      patient_info: {
        name: userData?.full_name || 'Not provided',
        age: age || 'Not provided',
        menopause_stage: userData?.menopause_stage || 'Not specified',
      },
      health_conditions: profileData?.health_conditions || {},
      current_medications: profileData?.medications || {},
      lifestyle_factors: profileData?.lifestyle_factors || {},
      symptom_summary: {
        total_entries: symptomLogs.length,
        period_days: 30,
        trends: symptomTrends,
        most_severe_symptoms: severeSymptoms,
      },
      daily_log: symptomLogs.map((log) => ({
        date: log.date,
        symptoms: log.symptoms,
        notes: log.notes,
      })),
      disclaimer:
        'This report is generated by MenoMind for informational purposes only. It is not a medical diagnosis. Please discuss all symptoms and concerns with your healthcare provider.',
    }

    return NextResponse.json({ data: report })
  } catch (error) {
    console.error('GET /api/export/report error:', error)
    return NextResponse.json(
      { error: 'Internal server error' },
      { status: 500 }
    )
  }
}
